// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkydNIYU7vlGzOmyVvfpFTwOKYQDbxVyc',
    appId: '1:650399473840:web:104a77f2f7905752dc5b75',
    messagingSenderId: '650399473840',
    projectId: 'afdal-al-uloom',
    authDomain: 'afdal-al-uloom.firebaseapp.com',
    storageBucket: 'afdal-al-uloom.firebasestorage.app',
    measurementId: 'G-HE1RFD14MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsluma0PP9fszA9Bju9Gs2j5bHzmHqBS4',
    appId: '1:650399473840:android:f1ff92985d91ad5bdc5b75',
    messagingSenderId: '650399473840',
    projectId: 'afdal-al-uloom',
    storageBucket: 'afdal-al-uloom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZp49EvZH4YtxViM8EJcBD33dh0Evyi74',
    appId: '1:650399473840:ios:5591f955aa3caea9dc5b75',
    messagingSenderId: '650399473840',
    projectId: 'afdal-al-uloom',
    storageBucket: 'afdal-al-uloom.firebasestorage.app',
    iosBundleId: 'com.afdaluloom.tilawat',
  );
}
