// Generates functions/src/lib/surahs.ts from lib/core/constants/surahs.dart,
// so the app and the Cloud Functions share one ayah table. Run from the repo
// root after changing the Dart list:
//
//   dart run tool/generate_surahs_ts.dart
//
// test/tool/generate_surahs_ts_test.dart fails while the two differ.
import 'dart:io';

import 'package:afdal_uloom_tilawat/core/constants/surahs.dart';

const surahsTsPath = 'functions/src/lib/surahs.ts';
const _countsPerLine = 10;

void main() {
  File(surahsTsPath).writeAsStringSync(renderSurahsTs());
  stdout.writeln('Wrote $surahsTsPath (${surahs.length} surahs).');
}

/// The content of [surahsTsPath].
String renderSurahsTs() {
  final lines = <String>[];
  for (var start = 0; start < surahs.length; start += _countsPerLine) {
    final row = surahs.skip(start).take(_countsPerLine);
    final counts = row.map((s) => s.ayahCount).join(', ');
    lines.add('  $counts, // ${row.first.number}-${row.last.number}');
  }
  return '''
// GENERATED by tool/generate_surahs_ts.dart from
// lib/core/constants/surahs.dart. Do not edit; change the Dart list and run
//   dart run tool/generate_surahs_ts.dart

/** Ayah count (Hafs) of each surah: AYAH_COUNTS[n - 1] is surah n. */
export const AYAH_COUNTS: readonly number[] = [
${lines.join('\n')}
];

export const SURAH_COUNT = AYAH_COUNTS.length;

/** Whether ayat [from]..[to] exist in surah [surah]. */
export function isValidAyahRange(surah: number, from: number, to: number): boolean {
  return Number.isInteger(surah) && Number.isInteger(from) && Number.isInteger(to)
    && surah >= 1 && surah <= SURAH_COUNT
    && from >= 1 && from <= to && to <= AYAH_COUNTS[surah - 1];
}
''';
}
